version: "3.9"

services:
  core:
    build:
      target: development
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: timescale/timescaledb:latest-pg12
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
